name: Build Stash Mobile Apps

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-mobile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5

    - name: Install Python packages
      run: |
        pip install flet==0.24.1
        pip install requests passlib

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --product-name "Stash" --build-name="1.0.0" --build-number=1

    - name: Build IPA
      run: |
        flutter config --no-analytics
        flet build ipa --product-name "Stash" --build-name="1.0.0" --build-number=1
        cd build/ios/archive/Runner.xcarchive
        mkdir -p Payload
        cp -r Products/Applications/Runner.app Payload/
        mv Payload/Runner.app Payload/Stash.app
        zip -r ../../../ipa/Stash.ipa Payload

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Stash-APK
        path: build/apk/

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Stash-IPA
        path: build/ipa/Stash.ipa
